# Generated by Django 4.0.4 on 2022-06-03 21:21

import app_areas_of_knowledges.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, verbose_name='name')),
                ('name_en', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('name_uk', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_uk', models.TextField(null=True, verbose_name='description')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='level')),
            ],
            options={
                'verbose_name': 'Levels of competence',
                'verbose_name_plural': 'Levels of competence',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesAndAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, verbose_name='name')),
                ('name_en', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('name_uk', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_category', models.BooleanField(verbose_name='is category')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_areas_of_knowledges.categoriesandareas', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Categories and areas',
                'verbose_name_plural': 'Categories and areas',
                'unique_together': {('name', 'parent')},
            },
        ),
    ]
