# Generated by Django 4.0.4 on 2022-05-03 12:50

import app_areas_of_knowledges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0003_competencelevels_alter_categoriesandareas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencelevels',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='lft',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='name_en',
            field=app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='name_uk',
            field=app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='rght',
            field=models.PositiveIntegerField(default=3, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=5, editable=False),
            preserve_default=False,
        ),
    ]
