# Generated by Django 4.0.4 on 2022-05-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0004_competencelevels_level_competencelevels_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencelevels',
            options={'ordering': ['my_order'], 'verbose_name': 'Levels of competence', 'verbose_name_plural': 'Levels of competence'},
        ),
        migrations.RemoveField(
            model_name='competencelevels',
            name='level',
        ),
        migrations.RemoveField(
            model_name='competencelevels',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='competencelevels',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='competencelevels',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='competencelevels',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
