# Generated by Django 4.0.4 on 2022-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0005_alter_competencelevels_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencelevels',
            options={'ordering': ['level'], 'verbose_name': 'Levels of competence', 'verbose_name_plural': 'Levels of competence'},
        ),
        migrations.RenameField(
            model_name="competencelevels",
            old_name="my_order",
            new_name="level",
        ),
    ]
