# Generated by Django 4.0.4 on 2022-05-04 17:56

import app_areas_of_knowledges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0007_competencelevels_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, verbose_name='name')),
                ('name_en', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('name_uk', app_areas_of_knowledges.models.NonStrippingCharField(max_length=150, null=True, verbose_name='name')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_uk', models.TextField(null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Road maps',
                'verbose_name_plural': 'Road maps',
            },
        ),
        migrations.CreateModel(
            name='RoadMapStructure',
            fields=[
                ('area1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_areas_of_knowledges.categoriesandareas', verbose_name='area')),
                ('order_in_roadmap', models.PositiveIntegerField(default=0, verbose_name='order in roadmap')),
                ('level_of_competence1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_areas_of_knowledges.competencelevels', verbose_name='level of competence')),
                ('road_map1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_areas_of_knowledges.roadmaps')),
            ],
            options={
                'verbose_name': 'Road map structure',
                'verbose_name_plural': 'Road map structure',
                'ordering': ['order_in_roadmap'],
            },
        ),
    ]
