# Generated by Django 4.0.4 on 2022-05-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0008_roadmaps_roadmapstructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapstructure',
            name='area1',
        ),
        migrations.RemoveField(
            model_name='roadmapstructure',
            name='level_of_competence1',
        ),
        migrations.RemoveField(
            model_name='roadmapstructure',
            name='road_map1',
        ),
        migrations.DeleteModel(
            name='RoadMaps',
        ),
        migrations.DeleteModel(
            name='RoadMapStructure',
        ),
    ]
