# Generated by Django 4.0.4 on 2022-05-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0009_remove_roadmapstructure_area1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesandareas',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoriesandareas',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='categoriesandareas',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
