# Generated by Django 4.0.4 on 2022-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas_of_knowledges', '0010_categoriesandareas_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesandareas',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categoriesandareas',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categoriesandareas',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
