# Generated by Django 4.0.4 on 2022-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicredentials',
            options={'verbose_name': 'API credentials', 'verbose_name_plural': 'API credentials'},
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='parameters',
            field=models.JSONField(verbose_name='parameters'),
        ),
    ]
