# Generated by Django 4.0.4 on 2022-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['level'], 'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projects',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='level'),
        ),
    ]
