# Generated by Django 4.0.4 on 2022-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0004_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='definition',
            field=models.CharField(max_length=255, null=True, verbose_name='definition'),
        ),
    ]
