# Generated by Django 4.0.4 on 2022-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0005_projects_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='definition_en',
            field=models.CharField(max_length=255, null=True, verbose_name='definition'),
        ),
        migrations.AddField(
            model_name='projects',
            name='definition_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='definition'),
        ),
    ]
